---
- name: Implement a real http squid proxy (batsquid)
  hosts: register
  tasks:
    - name: add http proxy variable
      lineinfile:
        path: /etc/environment
        regexp: '^HTTP_PROXY='
        line: 'HTTP_PROXY=http://batsquid.usersys.redhat.com:3128/'
        state: present

    - name: add https proxy variable
      lineinfile:
        path: /etc/environment
        regexp: '^HTTPS_PROXY='
        line: 'HTTPS_PROXY=https://batsquid.usersys.redhat.com:3128/'
        state: present

- name: Add regclass ACL
  hosts: proxy
  tasks:
    - name: add regclass ACL
      replace:
        path: /etc/squid/squid.conf
        regexp: '#acl regclass1 src regclass1.usersys.redhat.com'
        replace: 'acl regclass1 src regclass1.usersys.redhat.com'

    - name: add regclass http_access
      replace:
        path: /etc/squid/squid.conf
        regexp: '#http_access deny regclass1'
        replace: 'http_access deny regclass1'

    - name: restart squid
      service:
        name: squid
        state: restarted

    - name: Clear bash history
      shell: history -cw
