---
- name: add unsupported product
  hosts: register
  tasks:
  - name: copy oracle-java-restricted-maintenance.pem to server
    copy:
      src: ./pemfiles/oracle-java-restricted-maintenance.pem
      dest: /etc/pki/product-default/666.pem
      owner: root
      group: root
      mode: 0644

  - name: Clear bash history
    shell: history -cw
