---
- name: add iptables rules
  hosts: register
  tasks:
  - name: start iptables
    service:
      name: firewalld
      state: started

  - name: flush iptables
    iptables:
      flush: True

  - name: Clear bash history
    shell: history -cw
