---
- name: fix rhel product cert
  hosts: register
  tasks:
  - name: copy rhel7.4 product cert to server
    copy:
      src: ./pemfiles/rhel-7.4.pem
      dest: /etc/pki/product-default/69.pem
      owner: root
      group: root
      mode: 0644

  - name: Clear bash history
    shell: history -cw
