---
- name: correct redhat-uep.pem
  hosts: register
  tasks:
  - name: remove bad redhat-uep.pem
    file:
      state: absent
      path: /etc/rhsm/ca/redhat-uep.pem

  - name: copy good redhat-uep.pem
    copy:
      src: ./pemfiles/redhat-uep.pem
      dest: /etc/rhsm/ca/redhat-uep.pem
      owner: root
      group: root
      mode: 0644

  - name: Clear bash history
    shell: history -cw
