---
- name: Dual Register
  hosts: register
  tasks:
  - name: Register to RHSM
    redhat_subscription:
      username: {{ USERNAME }}
      password: {{ PASSWORD }}
      auto_attach: yes
      force_register: yes

  - name: Install Sat5 certs
    yum:
      name: http://thor.usersys.redhat.com/pub/rhn-org-trusted-ssl-cert-1.0-1.noarch.rpm
      state: present

  - name: Set RHSM release
    command: subscription-manager release --set=7.4
